name: Publish Deployment

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: ${{secrets.REGISTRY_URL}}
          always-auth: true
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Publish to registry
        run: |
          yarn publish:all 
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}